Repository web-architectures-project/SkillVista-backend, pull requests merged in 2023-10, with the labels that each got.

#21 Database Schema Completed
  prisma/schema.prisma
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: enhancement

#23 fix/ignore package lock
  .gitignore
  package-lock.json
Labels: enhancement

#19 Feature/setup api
  .vscode/settings.json
  package.json
  src/app.module.ts
  src/contacts/contacts.controller.ts
  src/contacts/contacts.module.ts
  src/contacts/contacts.service.ts
  src/contacts/dto/create-contact.dto.ts
  src/contacts/dto/update-contact.dto.ts
  src/contacts/entities/contact.entity.ts
  src/main.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.spec.ts
  src/prisma/prisma.service.ts
  src/profiles/dto/create-profile.dto.ts
  src/profiles/dto/update-profile.dto.ts
  src/profiles/entities/profile.entity.ts
  src/profiles/profiles.controller.ts
  src/profiles/profiles.module.ts
  src/profiles/profiles.service.ts
  src/reviews/dto/create-review.dto.ts
  src/reviews/dto/update-review.dto.ts
  src/reviews/entities/review.entity.ts
  src/reviews/reviews.controller.ts
  src/reviews/reviews.module.ts
  src/reviews/reviews.service.ts
  src/service_types/dto/create-service_type.dto.ts
  src/service_types/dto/update-service_type.dto.ts
  src/service_types/entities/service_type.entity.ts
  src/service_types/service_types.controller.ts
  src/service_types/service_types.module.ts
  src/service_types/service_types.service.ts
  src/services/dto/create-service.dto.ts
  src/services/dto/update-service.dto.ts
  src/services/entities/service.entity.ts
  src/services/services.controller.ts
  src/services/services.module.ts
  src/services/services.service.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#24 fix/minor fixes
  .eslintrc.js
  .gitignore
  src/contacts/contacts.controller.ts
  src/profiles/profiles.controller.ts
  src/reviews/reviews.controller.ts
  src/service_types/service_types.controller.ts
  src/services/services.controller.ts
  src/user/user.controller.ts
Labels: fix

#28 feature/CD Build
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: enhancement

#29 Register api
  package.json
  prisma/schema.prisma
  src/config/jwt.ts
  src/main.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/users/dto/create-user.dto.ts
  src/users/jwt-strategy.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#31 Remove docker-compose and ammend docs
  README.md
  docker-compose.yaml
Labels: documentation, fix

#34 feature/login api & features/profiles-api
  .github/workflows/on-pr.yml
  package.json
  src/profiles/dto/create-profile.dto.ts
  src/profiles/dto/update-profile.dto.ts
  src/profiles/profile.spec.ts
  src/profiles/profiles.controller.ts
  src/profiles/profiles.module.ts
  src/profiles/profiles.service.ts
  src/users/users.controller.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  src/users/users.spec.ts
Labels: enhancement, fix

#39 feature/reviews api and misc
  .github/workflows/on-pr.yml
  src/reviews/dto/create-review.dto.ts
  src/reviews/dto/update-review.dto.ts
  src/reviews/reviews.controller.ts
  src/reviews/reviews.service.ts
  src/reviews/reviews.spec.ts
Labels: feature

#40 Adds config for dependabot
  .github/dependabot.yml
Labels: feature

#41 fix/updates packages and docker
  Dockerfile
  database/Dockerfile
  package.json
Labels: fix

#43 fix/API Misc Fixes
  src/profiles/profile.spec.ts
  src/profiles/profiles.service.ts
  src/reviews/reviews.service.ts
  src/reviews/reviews.spec.ts
  src/service_types/service_types.service.ts
  src/service_types/service_types.spec.ts
  src/services/dto/create-service.dto.ts
  src/services/service.spec.ts
  src/services/services.service.ts
Labels: fix

#47 Fixes dockerfile
  .github/workflows/on-pr.yml
  Dockerfile
Labels: fix

#49 feature/jwt-and-auth
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/contacts/contact.spec.ts
  src/contacts/contacts.controller.ts
  src/contacts/contacts.service.ts
  src/main.ts
  src/profiles/profiles.controller.ts
  src/profiles/profiles.service.ts
  src/providers/dto/create-provider.dto.ts
  src/providers/dto/login-provider.dto.ts
  src/providers/dto/update-provider.dto.ts
  src/providers/entities/provider.entity.ts
  src/providers/providers.controller.ts
  src/providers/providers.module.ts
  src/providers/providers.service.ts
  src/providers/providers.spec.ts
  src/reviews/reviews.service.ts
  src/services/services.service.ts
  src/users/dto/create-user.dto.ts
  src/users/jwt-strategy.ts
  src/users/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
  src/users/users.spec.ts
  src/utils/guards/jwt-auth.guard.ts
  src/utils/guards/local-request.guard.ts
  src/utils/guards/user-ownership.guard.ts
Labels: feature

#50 fix/register fix
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/users.service.ts
  src/users/users.spec.ts
Labels: fix

#51 Enables CORS
  src/main.ts
Labels: fix
